[package]
name = "fireapp_backend"
version = "0.1.0"
authors = ["dmitry.chepurovskiy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
