version: '3.1'

services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: fireapp
      POSTGRES_DB: fireapp
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
